<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блог</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body class="body">
    <div class="container">
        <header class="header">
            <?=$menu?>
        </header>
        <main>
            <?=$breadcrumbs?>
            <?=$content?>
        </main>
        <footer class="footer">@ 2025</footer>
    </div>
</body>
</html>